/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/logic/controller.go
*/

package logic

import (
	time "time"

	db "github.com/WiredOnes/vibetrack/backend/internal/db"
	environment "github.com/WiredOnes/vibetrack/backend/internal/environment"
	model "github.com/WiredOnes/vibetrack/backend/internal/model"
	state "github.com/WiredOnes/vibetrack/backend/internal/state"
	telemetry "github.com/WiredOnes/vibetrack/backend/internal/telemetry"
)

func NewGetRepositoriesArg(
	token string,
) GetRepositoriesArg {
	return GetRepositoriesArg{
		Token: token,
	}
}

func NewGetRepositoriesRes(
	repositories []Repository,
) GetRepositoriesRes {
	return GetRepositoriesRes{
		Repositories: repositories,
	}
}

func NewAnalyzeRepositoryArg(
	repositoryID int,
	token string,
) AnalyzeRepositoryArg {
	return AnalyzeRepositoryArg{
		RepositoryID: repositoryID,
		Token:        token,
	}
}

func NewAnalyzeRepositoryRes(
	summary string,
	filesChanged []string,
	keyChanges []AnalyzeKeyChange,
) AnalyzeRepositoryRes {
	return AnalyzeRepositoryRes{
		Summary:      summary,
		FilesChanged: filesChanged,
		KeyChanges:   keyChanges,
	}
}

func NewAnalyzeKeyChange(
	type_ string,
	description string,
) AnalyzeKeyChange {
	return AnalyzeKeyChange{
		Type:        type_,
		Description: description,
	}
}

func NewAnalyzeCommitArg(
	repositoryID int,
	commitSHA string,
	token string,
) AnalyzeCommitArg {
	return AnalyzeCommitArg{
		RepositoryID: repositoryID,
		CommitSHA:    commitSHA,
		Token:        token,
	}
}

func NewAnalyzeCommitRes(
	summary string,
	filesChanged []string,
	keyChanges []AnalyzeKeyChange,
) AnalyzeCommitRes {
	return AnalyzeCommitRes{
		Summary:      summary,
		FilesChanged: filesChanged,
		KeyChanges:   keyChanges,
	}
}

func NewRepository(
	id int64,
	name string,
	fullName string,
	description string,
	private bool,
	defaultBranch string,
	updatedAt time.Time,
) Repository {
	return Repository{
		ID:            id,
		Name:          name,
		FullName:      fullName,
		Description:   description,
		Private:       private,
		DefaultBranch: defaultBranch,
		UpdatedAt:     updatedAt,
	}
}

func NewController(
	telemetry telemetry.Telemetry,
	environmentHolder environment.Holder,
	healthState state.HealthAdapter,
	pingDB db.PingAdapter,
) *controller {
	return &controller{
		Telemetry:         telemetry,
		environmentHolder: environmentHolder,
		healthState:       healthState,
		pingDB:            pingDB,
	}
}

func NewCheckArg() CheckArg {
	return CheckArg{}
}

func NewCheckRes(
	status model.HealthStatus,
) CheckRes {
	return CheckRes{
		Status: status,
	}
}

func NewUpdateHealthStatusArg() UpdateHealthStatusArg {
	return UpdateHealthStatusArg{}
}

func NewUpdateHealthStatusRes() UpdateHealthStatusRes {
	return UpdateHealthStatusRes{}
}

func NewEXCHANGEOAuthCodeArg(
	code string,
	clientID string,
	clientSecret string,
) ExchangeOAuthCodeArg {
	return ExchangeOAuthCodeArg{
		Code:         code,
		ClientID:     clientID,
		ClientSecret: clientSecret,
	}
}

func NewEXCHANGEOAuthCodeRes(
	token string,
) ExchangeOAuthCodeRes {
	return ExchangeOAuthCodeRes{
		Token: token,
	}
}
