/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/error_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/model/error.go
*/

package model

import (
	"fmt"
)

// Dummy
var _ fmt.Scanner

// NewUnknownError creates new unknownError error
func NewUnknownError(
) Error {
	return unknownError{
	}
}

var _ Error = unknownError{}

// Error returns text representation of error
func (e unknownError) Error() string {
	return "unknown"
}

// Message returns user-friendly message
func (e unknownError) Message() string {
	return "Unknown"
}

// Code returns error code
func (e unknownError) Code() ErrorCode {
	return ErrorCodeUnknown
}

// Unwrap returns underlying errors
func (e unknownError) Unwrap() []error {
	var errs []error
	return errs
}

// Is checks if error is of type unknownError
func (e unknownError) Is(target error) bool {
	_, ok := target.(unknownError)
	return ok
}

// NewInternalError creates new internalError error
func NewInternalError(
) Error {
	return internalError{
	}
}

var _ Error = internalError{}

// Error returns text representation of error
func (e internalError) Error() string {
	return "internal"
}

// Message returns user-friendly message
func (e internalError) Message() string {
	return "Internal"
}

// Code returns error code
func (e internalError) Code() ErrorCode {
	return ErrorCodeInternal
}

// Unwrap returns underlying errors
func (e internalError) Unwrap() []error {
	var errs []error
	return errs
}

// Is checks if error is of type internalError
func (e internalError) Is(target error) bool {
	_, ok := target.(internalError)
	return ok
}

// NewUnimplementedError creates new unimplementedError error
func NewUnimplementedError(
) Error {
	return unimplementedError{
	}
}

var _ Error = unimplementedError{}

// Error returns text representation of error
func (e unimplementedError) Error() string {
	return "unimplemented"
}

// Message returns user-friendly message
func (e unimplementedError) Message() string {
	return "Unimplemented"
}

// Code returns error code
func (e unimplementedError) Code() ErrorCode {
	return ErrorCodeUnimplemented
}

// Unwrap returns underlying errors
func (e unimplementedError) Unwrap() []error {
	var errs []error
	return errs
}

// Is checks if error is of type unimplementedError
func (e unimplementedError) Is(target error) bool {
	_, ok := target.(unimplementedError)
	return ok
}


