/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/enum_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/model/error.go
*/

package model

var ErrorCodeFromString = map[string]ErrorCode{
	"UNKNOWN": ErrorCodeUnknown,
	"OK": ErrorCodeOK,
	"BAD_REQUEST": ErrorCodeBadRequest,
	"UNAUTHENTICATED": ErrorCodeUnauthenticated,
	"PERMISSION_DENIED": ErrorCodePermissionDenied,
	"NOT_FOUND": ErrorCodeNotFound,
	"ALREADY_EXISTS": ErrorCodeAlreadyExists,
	"PRECONDITION_FAILED": ErrorCodePreconditionFailed,
	"RESOURCE_EXHAUSTED": ErrorCodeResourceExhausted,
	"TIMEOUT_EXCEEDED": ErrorCodeTimeoutExceeded,
	"INTERNAL": ErrorCodeInternal,
	"UNIMPLEMENTED": ErrorCodeUnimplemented,
}

var ErrorCodeToString = map[ErrorCode]string{
	ErrorCodeUnknown: "UNKNOWN",
	ErrorCodeOK: "OK",
	ErrorCodeBadRequest: "BAD_REQUEST",
	ErrorCodeUnauthenticated: "UNAUTHENTICATED",
	ErrorCodePermissionDenied: "PERMISSION_DENIED",
	ErrorCodeNotFound: "NOT_FOUND",
	ErrorCodeAlreadyExists: "ALREADY_EXISTS",
	ErrorCodePreconditionFailed: "PRECONDITION_FAILED",
	ErrorCodeResourceExhausted: "RESOURCE_EXHAUSTED",
	ErrorCodeTimeoutExceeded: "TIMEOUT_EXCEEDED",
	ErrorCodeInternal: "INTERNAL",
	ErrorCodeUnimplemented: "UNIMPLEMENTED",
}

func (e ErrorCode) String() string {
	if str, ok := ErrorCodeToString[e]; ok {
		return str
	}
    
	return ErrorCodeToString[ErrorCodeUnknown]
}