/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/enum_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/model/health.go
*/

package model

var HealthStatusFromString = map[string]HealthStatus{
	"UNKNOWN": HealthStatusUnknown,
	"SERVING": HealthStatusServing,
	"NOT_SERVING": HealthStatusNotServing,
}

var HealthStatusToString = map[HealthStatus]string{
	HealthStatusUnknown: "UNKNOWN",
	HealthStatusServing: "SERVING",
	HealthStatusNotServing: "NOT_SERVING",
}

func (e HealthStatus) String() string {
	if str, ok := HealthStatusToString[e]; ok {
		return str
	}
    
	return HealthStatusToString[HealthStatusUnknown]
}