/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/model/migration.go
*/

package model

import (
	time "time"
)

func NewMigration(
	version uint,
	name string,
	query string,
	appliedAt time.Time,
) Migration {
	return Migration{
		Version: version,
		Name: name,
		Query: query,
		AppliedAt: appliedAt,
	}
}
