/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/model/tx.go
*/

package model

func NewTxOptions(
	isolationLevel TxIsolationLevel,
	readOnly bool,
) TxOptions {
	return TxOptions{
		IsolationLevel: isolationLevel,
		ReadOnly: readOnly,
	}
}
