/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/enum_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/model/tx.go
*/

package model

var TxIsolationLevelFromString = map[string]TxIsolationLevel{
	"READ_UNCOMMITTED": TxIsolationLevelReadUncommitted,
	"READ_COMMITTED": TxIsolationLevelReadCommitted,
	"REPEATABLE_READ": TxIsolationLevelRepeatableRead,
	"SERIALIZABLE": TxIsolationLevelSerializable,
}

var TxIsolationLevelToString = map[TxIsolationLevel]string{
	TxIsolationLevelReadUncommitted: "READ_UNCOMMITTED",
	TxIsolationLevelReadCommitted: "READ_COMMITTED",
	TxIsolationLevelRepeatableRead: "REPEATABLE_READ",
	TxIsolationLevelSerializable: "SERIALIZABLE",
}

func (e TxIsolationLevel) String() string {
	if str, ok := TxIsolationLevelToString[e]; ok {
		return str
	}
    
	return TxIsolationLevelToString[TxIsolationLevelReadUncommitted]
}