/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/app/app.go
*/

package app

func NewApp(
	primitives Primitives,
	dependencies Dependencies,
	adapters Adapters,
	controllers Controllers,
	actions Actions,
	handlers Handlers,
	ports Ports,
) App {
	return App{
		Primitives: primitives,
		Dependencies: dependencies,
		Adapters: adapters,
		Controllers: controllers,
		Actions: actions,
		Handlers: handlers,
		Ports: ports,
	}
}
