/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/app/collections.go
*/

package app

import (
	clock "github.com/benbjohnson/clock"
	http "github.com/WiredOnes/vibetrack/backend/internal/http"
	api "github.com/WiredOnes/vibetrack/backend/api/http/v1"
	logic "github.com/WiredOnes/vibetrack/backend/internal/logic"
	graceful "github.com/leshless/golibrary/graceful"
	config "github.com/WiredOnes/vibetrack/backend/internal/config"
	fs "io/fs"
	telemetry "github.com/WiredOnes/vibetrack/backend/internal/telemetry"
	state "github.com/WiredOnes/vibetrack/backend/internal/state"
	environment "github.com/WiredOnes/vibetrack/backend/internal/environment"
	db "github.com/WiredOnes/vibetrack/backend/internal/db"
	interrupt "github.com/leshless/golibrary/interrupt"
)

func NewPrimitives(
	clock clock.Clock,
	interrupter interrupt.Interrupter,
	fs fs.FS,
) Primitives {
	return Primitives{
		Clock: clock,
		Interrupter: interrupter,
		FS: fs,
	}
}

func NewDependencies(
	gracefulRegistrator graceful.Registrator,
	gracefulTerminator graceful.Terminator,
	configHolder config.Holder,
	environmentHolder environment.Holder,
	logger telemetry.Logger,
	registry telemetry.Registry,
	telemetry telemetry.Telemetry,
) Dependencies {
	return Dependencies{
		GracefulRegistrator: gracefulRegistrator,
		GracefulTerminator: gracefulTerminator,
		ConfigHolder: configHolder,
		EnvironmentHolder: environmentHolder,
		Logger: logger,
		Registry: registry,
		Telemetry: telemetry,
	}
}

func NewClients(
	db db.Client,
) Clients {
	return Clients{
		DB: db,
	}
}

func NewAdapters(
	pingDB db.PingAdapter,
	txdb db.TxAdapter,
	healthState state.HealthAdapter,
) Adapters {
	return Adapters{
		PingDB: pingDB,
		TXDB: txdb,
		HealthState: healthState,
	}
}

func NewControllers(
	controller logic.Controller,
) Controllers {
	return Controllers{
		Controller: controller,
	}
}

func NewActions(
) Actions {
	return Actions{
	}
}

func NewHandlers(
	httpHandler api.StrictServerInterface,
) Handlers {
	return Handlers{
		HTTPHandler: httpHandler,
	}
}

func NewPorts(
	http http.Port,
) Ports {
	return Ports{
		HTTP: http,
	}
}
