/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/http/handler.go
*/

package http

import (
	telemetry "github.com/WiredOnes/vibetrack/backend/internal/telemetry"
	logic "github.com/WiredOnes/vibetrack/backend/internal/logic"
)

func NewHandler(
	telemetry telemetry.Telemetry,
	controller logic.Controller,
) *Handler {
	return &Handler{
		Telemetry: telemetry,
		controller: controller,
	}
}
