/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/http/port.go
*/

package http

import (
	telemetry "github.com/WiredOnes/vibetrack/backend/internal/telemetry"
	http "net/http"
)

func NewPort(
	telemetry telemetry.Telemetry,
	httpServer *http.Server,
) *port {
	return &port{
		Telemetry: telemetry,
		httpServer: httpServer,
	}
}
