/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/environment/holder.go
*/

package environment

func NewHolder(
	environment *Environment,
) *holder {
	return &holder{
		environment: environment,
	}
}
