// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package http

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	strictnethttp "github.com/oapi-codegen/runtime/strictmiddleware/nethttp"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for AICommitSummaryKeyChangesType.
const (
	ADDED    AICommitSummaryKeyChangesType = "ADDED"
	MODIFIED AICommitSummaryKeyChangesType = "MODIFIED"
	REMOVED  AICommitSummaryKeyChangesType = "REMOVED"
)

// Valid indicates whether the value is a known member of the AICommitSummaryKeyChangesType enum.
func (e AICommitSummaryKeyChangesType) Valid() bool {
	switch e {
	case ADDED:
		return true
	case MODIFIED:
		return true
	case REMOVED:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	NOTSERVING HealthStatus = "NOT_SERVING"
	SERVING    HealthStatus = "SERVING"
	UNKNOWN    HealthStatus = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case NOTSERVING:
		return true
	case SERVING:
		return true
	case UNKNOWN:
		return true
	default:
		return false
	}
}

// AICommitSummary defines model for AICommitSummary.
type AICommitSummary struct {
	FilesChanged []string `json:"files_changed"`
	KeyChanges   []struct {
		Description *string                        `json:"description,omitempty"`
		Type        *AICommitSummaryKeyChangesType `json:"type,omitempty"`
	} `json:"key_changes"`

	// Summary Краткое описание изменений
	Summary string `json:"summary"`
}

// AICommitSummaryKeyChangesType defines model for AICommitSummary.KeyChanges.Type.
type AICommitSummaryKeyChangesType string

// CheckHealthResponse defines model for CheckHealthResponse.
type CheckHealthResponse struct {
	// Status Service health status
	Status HealthStatus `json:"status"`
}

// Error defines model for Error.
type Error struct {
	// Message Human readable protected error message
	Message string `json:"message"`
}

// HealthStatus Service health status
type HealthStatus string

// OAuthTokenResponse defines model for OAuthTokenResponse.
type OAuthTokenResponse struct {
	Token string `json:"token"`
}

// Repository defines model for Repository.
type Repository struct {
	AiReadme      *string   `json:"ai_readme,omitempty"`
	AiSuggestion  *string   `json:"ai_suggestion,omitempty"`
	AiSummary     *string   `json:"ai_summary,omitempty"`
	DefaultBranch string    `json:"default_branch"`
	Description   string    `json:"description"`
	FullName      string    `json:"full_name"`
	Id            int       `json:"id"`
	Name          string    `json:"name"`
	Private       bool      `json:"private"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// OAuthCallbackParams defines parameters for OAuthCallback.
type OAuthCallbackParams struct {
	Code         string `form:"code" json:"code"`
	ClientId     string `form:"client_id" json:"client_id"`
	ClientSecret string `form:"client_secret" json:"client_secret"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Basic service healthcheck
	// (GET /health)
	CheckHealth(w http.ResponseWriter, r *http.Request)
	// GitHub OAuth callback
	// (GET /oauth/callback)
	OAuthCallback(w http.ResponseWriter, r *http.Request, params OAuthCallbackParams)
	// Получить список репозиториев пользователя
	// (GET /repositories)
	GetRepositories(w http.ResponseWriter, r *http.Request)
	// Получить информацию о конкретном репозитории
	// (GET /repositories/{repositoryID})
	GetRepositoriesRepositoryID(w http.ResponseWriter, r *http.Request, repositoryID int)
	// Получить AI-анализ проекта
	// (POST /repository/{repositoryID}/analyze)
	PostRepositoryRepositoryIDAnalyze(w http.ResponseWriter, r *http.Request, repositoryID int)
	// Получить AI-суммаризацию изменений в коммите
	// (POST /repository/{repositoryID}/{commitSHA}/analyze)
	PostRepositoryRepositoryIDCommitSHAAnalyze(w http.ResponseWriter, r *http.Request, repositoryID int, commitSHA string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Basic service healthcheck
// (GET /health)
func (_ Unimplemented) CheckHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GitHub OAuth callback
// (GET /oauth/callback)
func (_ Unimplemented) OAuthCallback(w http.ResponseWriter, r *http.Request, params OAuthCallbackParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить список репозиториев пользователя
// (GET /repositories)
func (_ Unimplemented) GetRepositories(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить информацию о конкретном репозитории
// (GET /repositories/{repositoryID})
func (_ Unimplemented) GetRepositoriesRepositoryID(w http.ResponseWriter, r *http.Request, repositoryID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить AI-анализ проекта
// (POST /repository/{repositoryID}/analyze)
func (_ Unimplemented) PostRepositoryRepositoryIDAnalyze(w http.ResponseWriter, r *http.Request, repositoryID int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Получить AI-суммаризацию изменений в коммите
// (POST /repository/{repositoryID}/{commitSHA}/analyze)
func (_ Unimplemented) PostRepositoryRepositoryIDCommitSHAAnalyze(w http.ResponseWriter, r *http.Request, repositoryID int, commitSHA string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CheckHealth operation middleware
func (siw *ServerInterfaceWrapper) CheckHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CheckHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// OAuthCallback operation middleware
func (siw *ServerInterfaceWrapper) OAuthCallback(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params OAuthCallbackParams

	// ------------- Required query parameter "code" -------------

	if paramValue := r.URL.Query().Get("code"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "code", r.URL.Query(), &params.Code, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code", Err: err})
		return
	}

	// ------------- Required query parameter "client_id" -------------

	if paramValue := r.URL.Query().Get("client_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "client_id"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "client_id", r.URL.Query(), &params.ClientId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		return
	}

	// ------------- Required query parameter "client_secret" -------------

	if paramValue := r.URL.Query().Get("client_secret"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "client_secret"})
		return
	}

	err = runtime.BindQueryParameterWithOptions("form", true, true, "client_secret", r.URL.Query(), &params.ClientSecret, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_secret", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.OAuthCallback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositories operation middleware
func (siw *ServerInterfaceWrapper) GetRepositories(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositories(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRepositoriesRepositoryID operation middleware
func (siw *ServerInterfaceWrapper) GetRepositoriesRepositoryID(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "repositoryID" -------------
	var repositoryID int

	err = runtime.BindStyledParameterWithOptions("simple", "repositoryID", chi.URLParam(r, "repositoryID"), &repositoryID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repositoryID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRepositoriesRepositoryID(w, r, repositoryID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRepositoryRepositoryIDAnalyze operation middleware
func (siw *ServerInterfaceWrapper) PostRepositoryRepositoryIDAnalyze(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "repositoryID" -------------
	var repositoryID int

	err = runtime.BindStyledParameterWithOptions("simple", "repositoryID", chi.URLParam(r, "repositoryID"), &repositoryID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repositoryID", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRepositoryRepositoryIDAnalyze(w, r, repositoryID)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PostRepositoryRepositoryIDCommitSHAAnalyze operation middleware
func (siw *ServerInterfaceWrapper) PostRepositoryRepositoryIDCommitSHAAnalyze(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "repositoryID" -------------
	var repositoryID int

	err = runtime.BindStyledParameterWithOptions("simple", "repositoryID", chi.URLParam(r, "repositoryID"), &repositoryID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "repositoryID", Err: err})
		return
	}

	// ------------- Path parameter "commitSHA" -------------
	var commitSHA string

	err = runtime.BindStyledParameterWithOptions("simple", "commitSHA", chi.URLParam(r, "commitSHA"), &commitSHA, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "commitSHA", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PostRepositoryRepositoryIDCommitSHAAnalyze(w, r, repositoryID, commitSHA)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.CheckHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/oauth/callback", wrapper.OAuthCallback)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/repositories", wrapper.GetRepositories)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/repositories/{repositoryID}", wrapper.GetRepositoriesRepositoryID)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/repository/{repositoryID}/analyze", wrapper.PostRepositoryRepositoryIDAnalyze)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/repository/{repositoryID}/{commitSHA}/analyze", wrapper.PostRepositoryRepositoryIDCommitSHAAnalyze)
	})

	return r
}

type CheckHealthRequestObject struct {
}

type CheckHealthResponseObject interface {
	VisitCheckHealthResponse(w http.ResponseWriter) error
}

type CheckHealth200JSONResponse CheckHealthResponse

func (response CheckHealth200JSONResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type CheckHealthdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CheckHealthdefaultJSONResponse) VisitCheckHealthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type OAuthCallbackRequestObject struct {
	Params OAuthCallbackParams
}

type OAuthCallbackResponseObject interface {
	VisitOAuthCallbackResponse(w http.ResponseWriter) error
}

type OAuthCallback200JSONResponse OAuthTokenResponse

func (response OAuthCallback200JSONResponse) VisitOAuthCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type OAuthCallbackdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response OAuthCallbackdefaultJSONResponse) VisitOAuthCallbackResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetRepositoriesRequestObject struct {
}

type GetRepositoriesResponseObject interface {
	VisitGetRepositoriesResponse(w http.ResponseWriter) error
}

type GetRepositories200JSONResponse []Repository

func (response GetRepositories200JSONResponse) VisitGetRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRepositoriesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetRepositoriesdefaultJSONResponse) VisitGetRepositoriesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type GetRepositoriesRepositoryIDRequestObject struct {
	RepositoryID int `json:"repositoryID"`
}

type GetRepositoriesRepositoryIDResponseObject interface {
	VisitGetRepositoriesRepositoryIDResponse(w http.ResponseWriter) error
}

type GetRepositoriesRepositoryID200JSONResponse Repository

func (response GetRepositoriesRepositoryID200JSONResponse) VisitGetRepositoriesRepositoryIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetRepositoriesRepositoryIDdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetRepositoriesRepositoryIDdefaultJSONResponse) VisitGetRepositoriesRepositoryIDResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostRepositoryRepositoryIDAnalyzeRequestObject struct {
	RepositoryID int `json:"repositoryID"`
}

type PostRepositoryRepositoryIDAnalyzeResponseObject interface {
	VisitPostRepositoryRepositoryIDAnalyzeResponse(w http.ResponseWriter) error
}

type PostRepositoryRepositoryIDAnalyze200JSONResponse AICommitSummary

func (response PostRepositoryRepositoryIDAnalyze200JSONResponse) VisitPostRepositoryRepositoryIDAnalyzeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostRepositoryRepositoryIDAnalyzedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PostRepositoryRepositoryIDAnalyzedefaultJSONResponse) VisitPostRepositoryRepositoryIDAnalyzeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

type PostRepositoryRepositoryIDCommitSHAAnalyzeRequestObject struct {
	RepositoryID int    `json:"repositoryID"`
	CommitSHA    string `json:"commitSHA"`
}

type PostRepositoryRepositoryIDCommitSHAAnalyzeResponseObject interface {
	VisitPostRepositoryRepositoryIDCommitSHAAnalyzeResponse(w http.ResponseWriter) error
}

type PostRepositoryRepositoryIDCommitSHAAnalyze200JSONResponse AICommitSummary

func (response PostRepositoryRepositoryIDCommitSHAAnalyze200JSONResponse) VisitPostRepositoryRepositoryIDCommitSHAAnalyzeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type PostRepositoryRepositoryIDCommitSHAAnalyzedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response PostRepositoryRepositoryIDCommitSHAAnalyzedefaultJSONResponse) VisitPostRepositoryRepositoryIDCommitSHAAnalyzeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)

	return json.NewEncoder(w).Encode(response.Body)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Basic service healthcheck
	// (GET /health)
	CheckHealth(ctx context.Context, request CheckHealthRequestObject) (CheckHealthResponseObject, error)
	// GitHub OAuth callback
	// (GET /oauth/callback)
	OAuthCallback(ctx context.Context, request OAuthCallbackRequestObject) (OAuthCallbackResponseObject, error)
	// Получить список репозиториев пользователя
	// (GET /repositories)
	GetRepositories(ctx context.Context, request GetRepositoriesRequestObject) (GetRepositoriesResponseObject, error)
	// Получить информацию о конкретном репозитории
	// (GET /repositories/{repositoryID})
	GetRepositoriesRepositoryID(ctx context.Context, request GetRepositoriesRepositoryIDRequestObject) (GetRepositoriesRepositoryIDResponseObject, error)
	// Получить AI-анализ проекта
	// (POST /repository/{repositoryID}/analyze)
	PostRepositoryRepositoryIDAnalyze(ctx context.Context, request PostRepositoryRepositoryIDAnalyzeRequestObject) (PostRepositoryRepositoryIDAnalyzeResponseObject, error)
	// Получить AI-суммаризацию изменений в коммите
	// (POST /repository/{repositoryID}/{commitSHA}/analyze)
	PostRepositoryRepositoryIDCommitSHAAnalyze(ctx context.Context, request PostRepositoryRepositoryIDCommitSHAAnalyzeRequestObject) (PostRepositoryRepositoryIDCommitSHAAnalyzeResponseObject, error)
}

type StrictHandlerFunc = strictnethttp.StrictHTTPHandlerFunc
type StrictMiddlewareFunc = strictnethttp.StrictHTTPMiddlewareFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CheckHealth operation middleware
func (sh *strictHandler) CheckHealth(w http.ResponseWriter, r *http.Request) {
	var request CheckHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CheckHealth(ctx, request.(CheckHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CheckHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CheckHealthResponseObject); ok {
		if err := validResponse.VisitCheckHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// OAuthCallback operation middleware
func (sh *strictHandler) OAuthCallback(w http.ResponseWriter, r *http.Request, params OAuthCallbackParams) {
	var request OAuthCallbackRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.OAuthCallback(ctx, request.(OAuthCallbackRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "OAuthCallback")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OAuthCallbackResponseObject); ok {
		if err := validResponse.VisitOAuthCallbackResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRepositories operation middleware
func (sh *strictHandler) GetRepositories(w http.ResponseWriter, r *http.Request) {
	var request GetRepositoriesRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRepositories(ctx, request.(GetRepositoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRepositories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRepositoriesResponseObject); ok {
		if err := validResponse.VisitGetRepositoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetRepositoriesRepositoryID operation middleware
func (sh *strictHandler) GetRepositoriesRepositoryID(w http.ResponseWriter, r *http.Request, repositoryID int) {
	var request GetRepositoriesRepositoryIDRequestObject

	request.RepositoryID = repositoryID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetRepositoriesRepositoryID(ctx, request.(GetRepositoriesRepositoryIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetRepositoriesRepositoryID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetRepositoriesRepositoryIDResponseObject); ok {
		if err := validResponse.VisitGetRepositoriesRepositoryIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostRepositoryRepositoryIDAnalyze operation middleware
func (sh *strictHandler) PostRepositoryRepositoryIDAnalyze(w http.ResponseWriter, r *http.Request, repositoryID int) {
	var request PostRepositoryRepositoryIDAnalyzeRequestObject

	request.RepositoryID = repositoryID

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostRepositoryRepositoryIDAnalyze(ctx, request.(PostRepositoryRepositoryIDAnalyzeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRepositoryRepositoryIDAnalyze")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostRepositoryRepositoryIDAnalyzeResponseObject); ok {
		if err := validResponse.VisitPostRepositoryRepositoryIDAnalyzeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PostRepositoryRepositoryIDCommitSHAAnalyze operation middleware
func (sh *strictHandler) PostRepositoryRepositoryIDCommitSHAAnalyze(w http.ResponseWriter, r *http.Request, repositoryID int, commitSHA string) {
	var request PostRepositoryRepositoryIDCommitSHAAnalyzeRequestObject

	request.RepositoryID = repositoryID
	request.CommitSHA = commitSHA

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PostRepositoryRepositoryIDCommitSHAAnalyze(ctx, request.(PostRepositoryRepositoryIDCommitSHAAnalyzeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PostRepositoryRepositoryIDCommitSHAAnalyze")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PostRepositoryRepositoryIDCommitSHAAnalyzeResponseObject); ok {
		if err := validResponse.VisitPostRepositoryRepositoryIDCommitSHAAnalyzeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
