/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/config/holder.go
*/

package config

func NewHolder(
	config *Config,
) *holder {
	return &holder{
		config: config,
	}
}
