/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/db/ping_adapter.go
*/

package db

func NewPingAdapter(
	client Client,
) *pingAdapter {
	return &pingAdapter{
		client: client,
	}
}
