// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const selectAllObjects = `-- name: SelectAllObjects :many
SELECT id FROM objects
`

func (q *Queries) SelectAllObjects(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, selectAllObjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
