/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/db/tx_adapter.go
*/

package db

import (
	telemetry "github.com/WiredOnes/vibetrack/backend/internal/telemetry"
)

func NewTxAdapter(
	telemetry telemetry.Telemetry,
	client Client,
) *txAdapter {
	return &txAdapter{
		Telemetry: telemetry,
		client: client,
	}
}
