/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/telemetry/interfaces.go
*/

package telemetry

func NewTelemetry(
	logger Logger,
	registry Registry,
) Telemetry {
	return Telemetry{
		Logger: logger,
		Registry: registry,
	}
}
