/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/telemetry/labels.go
*/

package telemetry

func newLabel(
	key string,
	value any,
) label {
	return label{
		key: key,
		value: value,
	}
}
