/*
AUTOGENERATED FILE. DO NOT EDIT.
MANUAL CHANGES WILL BE LOST.

Generated by tool: github.com/leshless/golibrary/constructor_generator
Generated from source file: /home/leshless/vibetrack/backend/internal/telemetry/registry.go
*/

package telemetry

import (
	prometheus "github.com/prometheus/client_golang/prometheus"
)

func newGauge(
	promGauge prometheus.Gauge,
) *gauge {
	return &gauge{
		promGauge: promGauge,
	}
}

func newGaugeNop(
) *gaugeNop {
	return &gaugeNop{
	}
}

func newCounter(
	promCounter prometheus.Counter,
) *counter {
	return &counter{
		promCounter: promCounter,
	}
}

func newCounterNop(
) *counterNop {
	return &counterNop{
	}
}

func newHistogram(
	promHistogram prometheus.Observer,
) *histogram {
	return &histogram{
		promHistogram: promHistogram,
	}
}

func newHistogramNop(
) *histogramNop {
	return &histogramNop{
	}
}

func newSummary(
	promSummary prometheus.Observer,
) *summary {
	return &summary{
		promSummary: promSummary,
	}
}

func newSummaryNop(
) *summaryNop {
	return &summaryNop{
	}
}
